export const biMentoradosRanking = [
  {
    "rank": 1,
    "name": "Priscila Gomes",
    "level": "A",
    "state": "GO",
    "bought": 122000,
    "soldLabel": "R$189.000",
    "sold": 189000,
    "profit": 67000,
    "traffic": 860,
    "roi": 77.9,
    "performance": null
  },
  {
    "rank": 2,
    "name": "Amanda Barbosa",
    "level": "A",
    "state": "SP",
    "bought": 112000,
    "soldLabel": "R$178.000",
    "sold": 178000,
    "profit": 66000,
    "traffic": 930,
    "roi": 71,
    "performance": null
  },
  {
    "rank": 3,
    "name": "Thiago Oliveira",
    "level": "A",
    "state": "SP",
    "bought": 122000,
    "soldLabel": "R$188.000",
    "sold": 188000,
    "profit": 66000,
    "traffic": 670,
    "roi": 98.5,
    "performance": null
  },
  {
    "rank": 4,
    "name": "Gabriel Gomes",
    "level": "A",
    "state": "RJ",
    "bought": 112000,
    "soldLabel": "R$177.000",
    "sold": 177000,
    "profit": 65000,
    "traffic": 740,
    "roi": 87.8,
    "performance": null
  },
  {
    "rank": 5,
    "name": "Isabela Oliveira",
    "level": "A",
    "state": "RJ",
    "bought": 113000,
    "soldLabel": "R$177.000",
    "sold": 177000,
    "profit": 64000,
    "traffic": 550,
    "roi": 116.4,
    "performance": null
  },
  {
    "rank": 6,
    "name": "Gustavo Moraes",
    "level": "A",
    "state": "PR",
    "bought": 133000,
    "soldLabel": "R$194.000",
    "sold": 194000,
    "profit": 61000,
    "traffic": 990,
    "roi": 61.6,
    "performance": null
  },
  {
    "rank": 7,
    "name": "Marcelo Oliveira",
    "level": "A",
    "state": "SC",
    "bought": 103000,
    "soldLabel": "R$164.000",
    "sold": 164000,
    "profit": 61000,
    "traffic": 440,
    "roi": 138.6,
    "performance": null
  },
  {
    "rank": 8,
    "name": "Bruno Pereira",
    "level": "A",
    "state": "RJ",
    "bought": 113000,
    "soldLabel": "R$173.000",
    "sold": 173000,
    "profit": 60000,
    "traffic": 940,
    "roi": 63.8,
    "performance": null
  },
  {
    "rank": 9,
    "name": "Marcelo Moraes",
    "level": "A",
    "state": "SP",
    "bought": 123000,
    "soldLabel": "R$183.000",
    "sold": 183000,
    "profit": 60000,
    "traffic": 870,
    "roi": 69,
    "performance": null
  },
  {
    "rank": 10,
    "name": "Mariana Lima",
    "level": "A",
    "state": "SC",
    "bought": 133000,
    "soldLabel": "R$193.000",
    "sold": 193000,
    "profit": 60000,
    "traffic": 800,
    "roi": 75,
    "performance": null
  },
  {
    "rank": 11,
    "name": "Andressa Moraes",
    "level": "A",
    "state": "RJ",
    "bought": 113000,
    "soldLabel": "R$172.000",
    "sold": 172000,
    "profit": 59000,
    "traffic": 750,
    "roi": 78.7,
    "performance": null
  },
  {
    "rank": 12,
    "name": "Thiago Lima",
    "level": "A",
    "state": "SP",
    "bought": 124000,
    "soldLabel": "R$183.000",
    "sold": 183000,
    "profit": 59000,
    "traffic": 680,
    "roi": 86.8,
    "performance": null
  },
  {
    "rank": 13,
    "name": "Beatriz Alves",
    "level": "A",
    "state": "PR",
    "bought": 103000,
    "soldLabel": "R$161.000",
    "sold": 161000,
    "profit": 58000,
    "traffic": 820,
    "roi": 70.7,
    "performance": null
  },
  {
    "rank": 14,
    "name": "Felipe Lima",
    "level": "A",
    "state": "RJ",
    "bought": 114000,
    "soldLabel": "R$172.000",
    "sold": 172000,
    "profit": 58000,
    "traffic": 570,
    "roi": 101.8,
    "performance": null
  },
  {
    "rank": 15,
    "name": "Pedro Moraes",
    "level": "A",
    "state": "SC",
    "bought": 104000,
    "soldLabel": "R$161.000",
    "sold": 161000,
    "profit": 57000,
    "traffic": 640,
    "roi": 89.1,
    "performance": null
  },
  {
    "rank": 16,
    "name": "Marcelo Santos",
    "level": "A",
    "state": "SP",
    "bought": 125000,
    "soldLabel": "R$179.000",
    "sold": 179000,
    "profit": 54000,
    "traffic": 880,
    "roi": 61.4,
    "performance": null
  },
  {
    "rank": 17,
    "name": "Mariana Almeida",
    "level": "A",
    "state": "RJ",
    "bought": 114000,
    "soldLabel": "R$167.000",
    "sold": 167000,
    "profit": 53000,
    "traffic": 960,
    "roi": 55.2,
    "performance": null
  },
  {
    "rank": 18,
    "name": "Thiago Santos",
    "level": "A",
    "state": "RJ",
    "bought": 144000,
    "soldLabel": "R$197.000",
    "sold": 197000,
    "profit": 53000,
    "traffic": 270,
    "roi": 196.3,
    "performance": null
  },
  {
    "rank": 19,
    "name": "Isabela Santos",
    "level": "A",
    "state": "SC",
    "bought": 134000,
    "soldLabel": "R$187.000",
    "sold": 187000,
    "profit": 53000,
    "traffic": 150,
    "roi": 353.3,
    "performance": null
  },
  {
    "rank": 20,
    "name": "Andressa Santos",
    "level": "A",
    "state": "RJ",
    "bought": 115000,
    "soldLabel": "R$168.000",
    "sold": 168000,
    "profit": 53000,
    "traffic": 770,
    "roi": 68.8,
    "performance": null
  },
  {
    "rank": 21,
    "name": "Pedro Nascimento",
    "level": "A",
    "state": "RJ",
    "bought": 145000,
    "soldLabel": "R$197.000",
    "sold": 197000,
    "profit": 52000,
    "traffic": 930,
    "roi": 55.9,
    "performance": null
  },
  {
    "rank": 22,
    "name": "Lucas Nascimento",
    "level": "A",
    "state": "RS",
    "bought": 135000,
    "soldLabel": "R$187.000",
    "sold": 187000,
    "profit": 52000,
    "traffic": 810,
    "roi": 64.2,
    "performance": null
  },
  {
    "rank": 23,
    "name": "Camila Freitas",
    "level": "A",
    "state": "SP",
    "bought": 125000,
    "soldLabel": "R$177.000",
    "sold": 177000,
    "profit": 52000,
    "traffic": 700,
    "roi": 74.3,
    "performance": null
  },
  {
    "rank": 24,
    "name": "Daniela Rodrigues",
    "level": "A",
    "state": "PE",
    "bought": 135000,
    "soldLabel": "R$186.000",
    "sold": 186000,
    "profit": 51000,
    "traffic": 630,
    "roi": 81,
    "performance": null
  },
  {
    "rank": 25,
    "name": "Letícia Rodrigues",
    "level": "A",
    "state": "MG",
    "bought": 145000,
    "soldLabel": "R$195.000",
    "sold": 195000,
    "profit": 50000,
    "traffic": 740,
    "roi": 67.6,
    "performance": null
  },
  {
    "rank": 26,
    "name": "Felipe Martins",
    "level": "A",
    "state": "RS",
    "bought": 136000,
    "soldLabel": "R$182.000",
    "sold": 182000,
    "profit": 46000,
    "traffic": 170,
    "roi": 270.6,
    "performance": null
  },
  {
    "rank": 27,
    "name": "Letícia Carvalho",
    "level": "A",
    "state": "SP",
    "bought": 126000,
    "soldLabel": "R$172.000",
    "sold": 172000,
    "profit": 46000,
    "traffic": 900,
    "roi": 51.1,
    "performance": null
  },
  {
    "rank": 28,
    "name": "Thiago Martins",
    "level": "A",
    "state": "RJ",
    "bought": 145000,
    "soldLabel": "R$190.000",
    "sold": 190000,
    "profit": 45000,
    "traffic": 280,
    "roi": 160.7,
    "performance": null
  },
  {
    "rank": 29,
    "name": "Lucas Ferreira",
    "level": "A",
    "state": "PE",
    "bought": 136000,
    "soldLabel": "R$181.000",
    "sold": 181000,
    "profit": 45000,
    "traffic": 830,
    "roi": 54.2,
    "performance": null
  },
  {
    "rank": 30,
    "name": "Ana Ferreira",
    "level": "A",
    "state": "MG",
    "bought": 146000,
    "soldLabel": "R$189.000",
    "sold": 189000,
    "profit": 43000,
    "traffic": 940,
    "roi": 45.7,
    "performance": null
  },
  {
    "rank": 31,
    "name": "Daniela Araújo",
    "level": "A",
    "state": "SP",
    "bought": 136000,
    "soldLabel": "R$179.000",
    "sold": 179000,
    "profit": 43000,
    "traffic": 640,
    "roi": 67.2,
    "performance": null
  },
  {
    "rank": 32,
    "name": "Eduardo Araújo",
    "level": "A",
    "state": "PR",
    "bought": 146000,
    "soldLabel": "R$188.000",
    "sold": 188000,
    "profit": 42000,
    "traffic": 760,
    "roi": 55.3,
    "performance": null
  },
  {
    "rank": 33,
    "name": "Camila Silva",
    "level": "B",
    "state": "MG",
    "bought": 147000,
    "soldLabel": "R$184.000",
    "sold": 184000,
    "profit": 37000,
    "traffic": 300,
    "roi": 123.3,
    "performance": null
  },
  {
    "rank": 34,
    "name": "Carlos Ribeiro",
    "level": "B",
    "state": "PR",
    "bought": 147000,
    "soldLabel": "R$182.000",
    "sold": 182000,
    "profit": 35000,
    "traffic": 960,
    "roi": 36.5,
    "performance": null
  },
  {
    "rank": 35,
    "name": "Carlos Gomes",
    "level": "B",
    "state": "RJ",
    "bought": 68000,
    "soldLabel": "R$102.000",
    "sold": 102000,
    "profit": 34000,
    "traffic": 400,
    "roi": 85,
    "performance": null
  },
  {
    "rank": 36,
    "name": "Fernanda Oliveira",
    "level": "B",
    "state": "PR",
    "bought": 57000,
    "soldLabel": "R$90.000",
    "sold": 90000,
    "profit": 33000,
    "traffic": 270,
    "roi": 122.2,
    "performance": null
  },
  {
    "rank": 37,
    "name": "Vanessa Souza",
    "level": "B",
    "state": "RJ",
    "bought": 68000,
    "soldLabel": "R$101.000",
    "sold": 101000,
    "profit": 33000,
    "traffic": 220,
    "roi": 150,
    "performance": null
  },
  {
    "rank": 38,
    "name": "Eduardo Costa",
    "level": "B",
    "state": "SC",
    "bought": 147000,
    "soldLabel": "R$180.000",
    "sold": 180000,
    "profit": 33000,
    "traffic": 770,
    "roi": 42.9,
    "performance": null
  },
  {
    "rank": 39,
    "name": "Leonardo Almeida",
    "level": "B",
    "state": "SC",
    "bought": 57000,
    "soldLabel": "R$90.000",
    "sold": 90000,
    "profit": 33000,
    "traffic": 930,
    "roi": 35.5,
    "performance": null
  },
  {
    "rank": 40,
    "name": "Daniela Freitas",
    "level": "B",
    "state": "SP",
    "bought": 79000,
    "soldLabel": "R$111.000",
    "sold": 111000,
    "profit": 32000,
    "traffic": 530,
    "roi": 60.4,
    "performance": null
  },
  {
    "rank": 41,
    "name": "Diego Pereira",
    "level": "B",
    "state": "RJ",
    "bought": 69000,
    "soldLabel": "R$100.000",
    "sold": 100000,
    "profit": 31000,
    "traffic": 600,
    "roi": 51.7,
    "performance": null
  },
  {
    "rank": 42,
    "name": "Felipe Moraes",
    "level": "B",
    "state": "PR",
    "bought": 58000,
    "soldLabel": "R$89.000",
    "sold": 89000,
    "profit": 31000,
    "traffic": 470,
    "roi": 66,
    "performance": null
  },
  {
    "rank": 43,
    "name": "Fernanda Gomes",
    "level": "B",
    "state": "SC",
    "bought": 58000,
    "soldLabel": "R$89.000",
    "sold": 89000,
    "profit": 31000,
    "traffic": 290,
    "roi": 106.9,
    "performance": null
  },
  {
    "rank": 44,
    "name": "Rodrigo Rodrigues",
    "level": "B",
    "state": "SP",
    "bought": 79000,
    "soldLabel": "R$110.000",
    "sold": 110000,
    "profit": 31000,
    "traffic": 350,
    "roi": 88.6,
    "performance": null
  },
  {
    "rank": 45,
    "name": "Monique Freitas",
    "level": "B",
    "state": "RJ",
    "bought": 69000,
    "soldLabel": "R$99.000",
    "sold": 99000,
    "profit": 30000,
    "traffic": 420,
    "roi": 71.4,
    "performance": null
  },
  {
    "rank": 46,
    "name": "Leonardo Souza",
    "level": "B",
    "state": "RS",
    "bought": 58000,
    "soldLabel": "R$88.000",
    "sold": 88000,
    "profit": 30000,
    "traffic": 950,
    "roi": 31.6,
    "performance": null
  },
  {
    "rank": 47,
    "name": "Vanessa Ferreira",
    "level": "B",
    "state": "RS",
    "bought": 90000,
    "soldLabel": "R$119.000",
    "sold": 119000,
    "profit": 29000,
    "traffic": 660,
    "roi": 43.9,
    "performance": null
  },
  {
    "rank": 48,
    "name": "Vanessa Rodrigues",
    "level": "B",
    "state": "MG",
    "bought": 69000,
    "soldLabel": "R$98.000",
    "sold": 98000,
    "profit": 29000,
    "traffic": 230,
    "roi": 126.1,
    "performance": null
  },
  {
    "rank": 49,
    "name": "Larissa Pereira",
    "level": "B",
    "state": "SC",
    "bought": 59000,
    "soldLabel": "R$87.000",
    "sold": 87000,
    "profit": 28000,
    "traffic": 490,
    "roi": 57.1,
    "performance": null
  },
  {
    "rank": 50,
    "name": "Leonardo Ferreira",
    "level": "B",
    "state": "SP",
    "bought": 80000,
    "soldLabel": "R$108.000",
    "sold": 108000,
    "profit": 28000,
    "traffic": 550,
    "roi": 50.9,
    "performance": null
  },
  {
    "rank": 51,
    "name": "Rafael Freitas",
    "level": "B",
    "state": "RS",
    "bought": 59000,
    "soldLabel": "R$87.000",
    "sold": 87000,
    "profit": 28000,
    "traffic": 300,
    "roi": 93.3,
    "performance": null
  },
  {
    "rank": 52,
    "name": "Bruno Nascimento",
    "level": "B",
    "state": "BA",
    "bought": 90000,
    "soldLabel": "R$118.000",
    "sold": 118000,
    "profit": 28000,
    "traffic": 480,
    "roi": 58.3,
    "performance": null
  },
  {
    "rank": 53,
    "name": "Diego Carvalho",
    "level": "B",
    "state": "RJ",
    "bought": 70000,
    "soldLabel": "R$97.000",
    "sold": 97000,
    "profit": 27000,
    "traffic": 620,
    "roi": 43.5,
    "performance": null
  },
  {
    "rank": 54,
    "name": "Eduardo Moraes",
    "level": "B",
    "state": "SP",
    "bought": 48000,
    "soldLabel": "R$75.000",
    "sold": 75000,
    "profit": 27000,
    "traffic": 360,
    "roi": 75,
    "performance": null
  },
  {
    "rank": 55,
    "name": "Amanda Gomes",
    "level": "B",
    "state": "SP",
    "bought": 48000,
    "soldLabel": "R$75.000",
    "sold": 75000,
    "profit": 27000,
    "traffic": 170,
    "roi": 158.8,
    "performance": null
  },
  {
    "rank": 56,
    "name": "Beatriz Nascimento",
    "level": "B",
    "state": "SP",
    "bought": 80000,
    "soldLabel": "R$107.000",
    "sold": 107000,
    "profit": 27000,
    "traffic": 360,
    "roi": 75,
    "performance": null
  },
  {
    "rank": 57,
    "name": "Priscila Alves",
    "level": "B",
    "state": "MG",
    "bought": 100000,
    "soldLabel": "R$127.000",
    "sold": 127000,
    "profit": 27000,
    "traffic": 410,
    "roi": 65.9,
    "performance": null
  },
  {
    "rank": 58,
    "name": "Priscila Lima",
    "level": "B",
    "state": "BA",
    "bought": 60000,
    "soldLabel": "R$87.000",
    "sold": 87000,
    "profit": 27000,
    "traffic": 960,
    "roi": 28.1,
    "performance": null
  },
  {
    "rank": 59,
    "name": "Monique Santos",
    "level": "B",
    "state": "MG",
    "bought": 70000,
    "soldLabel": "R$96.000",
    "sold": 96000,
    "profit": 26000,
    "traffic": 430,
    "roi": 60.5,
    "performance": null
  },
  {
    "rank": 60,
    "name": "Gustavo Nascimento",
    "level": "B",
    "state": "MG",
    "bought": 71000,
    "soldLabel": "R$97.000",
    "sold": 97000,
    "profit": 26000,
    "traffic": 240,
    "roi": 108.3,
    "performance": null
  },
  {
    "rank": 61,
    "name": "Rodrigo Carvalho",
    "level": "B",
    "state": "RS",
    "bought": 60000,
    "soldLabel": "R$85.000",
    "sold": 85000,
    "profit": 25000,
    "traffic": 500,
    "roi": 50,
    "performance": null
  },
  {
    "rank": 62,
    "name": "Eduardo Pereira",
    "level": "B",
    "state": "SP",
    "bought": 49000,
    "soldLabel": "R$74.000",
    "sold": 74000,
    "profit": 25000,
    "traffic": 370,
    "roi": 67.6,
    "performance": null
  },
  {
    "rank": 63,
    "name": "Vanessa Martins",
    "level": "B",
    "state": "BA",
    "bought": 91000,
    "soldLabel": "R$115.000",
    "sold": 115000,
    "profit": 24000,
    "traffic": 680,
    "roi": 35.3,
    "performance": null
  },
  {
    "rank": 64,
    "name": "Amanda Souza",
    "level": "B",
    "state": "MG",
    "bought": 71000,
    "soldLabel": "R$94.000",
    "sold": 94000,
    "profit": 23000,
    "traffic": 630,
    "roi": 36.5,
    "performance": null
  },
  {
    "rank": 65,
    "name": "Rodrigo Martins",
    "level": "B",
    "state": "MG",
    "bought": 101000,
    "soldLabel": "R$124.000",
    "sold": 124000,
    "profit": 23000,
    "traffic": 800,
    "roi": 28.8,
    "performance": null
  },
  {
    "rank": 66,
    "name": "Priscila Martins",
    "level": "B",
    "state": "SP",
    "bought": 81000,
    "soldLabel": "R$104.000",
    "sold": 104000,
    "profit": 23000,
    "traffic": 560,
    "roi": 41.1,
    "performance": null
  },
  {
    "rank": 67,
    "name": "Daniela Barbosa",
    "level": "B",
    "state": "RJ",
    "bought": 38000,
    "soldLabel": "R$61.000",
    "sold": 61000,
    "profit": 23000,
    "traffic": 240,
    "roi": 95.8,
    "performance": null
  },
  {
    "rank": 68,
    "name": "Bruno Costa",
    "level": "B",
    "state": "SP",
    "bought": 91000,
    "soldLabel": "R$114.000",
    "sold": 114000,
    "profit": 23000,
    "traffic": 490,
    "roi": 46.9,
    "performance": null
  },
  {
    "rank": 69,
    "name": "Beatriz Costa",
    "level": "B",
    "state": "RJ",
    "bought": 82000,
    "soldLabel": "R$105.000",
    "sold": 105000,
    "profit": 23000,
    "traffic": 380,
    "roi": 60.5,
    "performance": null
  },
  {
    "rank": 70,
    "name": "Juliana Costa",
    "level": "B",
    "state": "MG",
    "bought": 101000,
    "soldLabel": "R$123.000",
    "sold": 123000,
    "profit": 22000,
    "traffic": 610,
    "roi": 36.1,
    "performance": null
  },
  {
    "rank": 71,
    "name": "Rodrigo Gomes",
    "level": "B",
    "state": "RJ",
    "bought": 38000,
    "soldLabel": "R$60.000",
    "sold": 60000,
    "profit": 22000,
    "traffic": 900,
    "roi": 24.4,
    "performance": null
  },
  {
    "rank": 72,
    "name": "Marcelo Almeida",
    "level": "B",
    "state": "PR",
    "bought": 102000,
    "soldLabel": "R$123.000",
    "sold": 123000,
    "profit": 21000,
    "traffic": 420,
    "roi": 50,
    "performance": null
  },
  {
    "rank": 73,
    "name": "Gustavo Almeida",
    "level": "B",
    "state": "RJ",
    "bought": 111000,
    "soldLabel": "R$131.000",
    "sold": 131000,
    "profit": 20000,
    "traffic": 540,
    "roi": 37,
    "performance": null
  },
  {
    "rank": 74,
    "name": "Gustavo Barbosa",
    "level": "B",
    "state": "GO",
    "bought": 92000,
    "soldLabel": "R$110.000",
    "sold": 110000,
    "profit": 18000,
    "traffic": 690,
    "roi": 26.1,
    "performance": null
  },
  {
    "rank": 75,
    "name": "Beatriz Barbosa",
    "level": "B",
    "state": "MG",
    "bought": 102000,
    "soldLabel": "R$119.000",
    "sold": 119000,
    "profit": 17000,
    "traffic": 810,
    "roi": 21,
    "performance": null
  },
  {
    "rank": 76,
    "name": "Mariana Ribeiro",
    "level": "B",
    "state": "SP",
    "bought": 93000,
    "soldLabel": "R$110.000",
    "sold": 110000,
    "profit": 17000,
    "traffic": 510,
    "roi": 33.3,
    "performance": null
  },
  {
    "rank": 77,
    "name": "Juliana Gomes",
    "level": "B",
    "state": "PR",
    "bought": 102000,
    "soldLabel": "R$118.000",
    "sold": 118000,
    "profit": 16000,
    "traffic": 620,
    "roi": 25.8,
    "performance": null
  },
  {
    "rank": 78,
    "name": "Felipe Rodrigues",
    "level": "C",
    "state": "SP",
    "bought": 35000,
    "soldLabel": "R$46.000",
    "sold": 46000,
    "profit": 11000,
    "traffic": 860,
    "roi": 12.8,
    "performance": null
  },
  {
    "rank": 79,
    "name": "Mariana Martins",
    "level": "C",
    "state": "SP",
    "bought": 35000,
    "soldLabel": "R$45.000",
    "sold": 45000,
    "profit": 10000,
    "traffic": 400,
    "roi": 25,
    "performance": null
  },
  {
    "rank": 80,
    "name": "Vinícius Ferreira",
    "level": "C",
    "state": "SP",
    "bought": 36000,
    "soldLabel": "R$46.000",
    "sold": 46000,
    "profit": 10000,
    "traffic": 210,
    "roi": 47.6,
    "performance": null
  },
  {
    "rank": 81,
    "name": "Camila Araújo",
    "level": "C",
    "state": "PE",
    "bought": 46000,
    "soldLabel": "R$56.000",
    "sold": 56000,
    "profit": 10000,
    "traffic": 990,
    "roi": 10.1,
    "performance": null
  },
  {
    "rank": 82,
    "name": "Larissa Araújo",
    "level": "C",
    "state": "SP",
    "bought": 36000,
    "soldLabel": "R$45.000",
    "sold": 45000,
    "profit": 9000,
    "traffic": 870,
    "roi": 10.3,
    "performance": null
  },
  {
    "rank": 83,
    "name": "Letícia Ribeiro",
    "level": "C",
    "state": "PE",
    "bought": 47000,
    "soldLabel": "R$55.000",
    "sold": 55000,
    "profit": 8000,
    "traffic": 340,
    "roi": 23.5,
    "performance": null
  },
  {
    "rank": 84,
    "name": "Vinícius Ribeiro",
    "level": "C",
    "state": "SP",
    "bought": 37000,
    "soldLabel": "R$45.000",
    "sold": 45000,
    "profit": 8000,
    "traffic": 230,
    "roi": 34.8,
    "performance": null
  },
  {
    "rank": 85,
    "name": "Diego Oliveira",
    "level": "C",
    "state": "SP",
    "bought": 47000,
    "soldLabel": "R$55.000",
    "sold": 55000,
    "profit": 8000,
    "traffic": 160,
    "roi": 50,
    "performance": null
  },
  {
    "rank": 86,
    "name": "Larissa Oliveira",
    "level": "C",
    "state": "RJ",
    "bought": 37000,
    "soldLabel": "R$44.000",
    "sold": 44000,
    "profit": 7000,
    "traffic": 890,
    "roi": 7.9,
    "performance": null
  },
  {
    "rank": 87,
    "name": "Mariana Ribeiro",
    "level": "C",
    "state": "RS",
    "bought": 76000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 890,
    "roi": null,
    "performance": null
  },
  {
    "rank": 88,
    "name": "Mariana Souza",
    "level": "D",
    "state": "RJ",
    "bought": 116000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 640,
    "roi": null,
    "performance": null
  },
  {
    "rank": 89,
    "name": "Mariana Costa",
    "level": "D",
    "state": "SC",
    "bought": 75000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 1000,
    "roi": null,
    "performance": null
  },
  {
    "rank": 90,
    "name": "Bruno Santos",
    "level": "C",
    "state": "SP",
    "bought": 34000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 510,
    "roi": null,
    "performance": null
  },
  {
    "rank": 91,
    "name": "Bruno Nascimento",
    "level": "D",
    "state": "PR",
    "bought": 74000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 260,
    "roi": null,
    "performance": null
  },
  {
    "rank": 92,
    "name": "Bruno Freitas",
    "level": "C",
    "state": "GO",
    "bought": 33000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 620,
    "roi": null,
    "performance": null
  },
  {
    "rank": 93,
    "name": "Bruno Rodrigues",
    "level": "D",
    "state": "MG",
    "bought": 72000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 370,
    "roi": null,
    "performance": null
  },
  {
    "rank": 94,
    "name": "Amanda Gomes",
    "level": "C",
    "state": "BA",
    "bought": 32000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 730,
    "roi": null,
    "performance": null
  },
  {
    "rank": 95,
    "name": "Amanda Ribeiro",
    "level": "D",
    "state": "SP",
    "bought": 111000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 240,
    "roi": null,
    "performance": null
  },
  {
    "rank": 96,
    "name": "Amanda Oliveira",
    "level": "C",
    "state": "RS",
    "bought": 30000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 850,
    "roi": null,
    "performance": null
  },
  {
    "rank": 97,
    "name": "Diego Ferreira",
    "level": "D",
    "state": "SP",
    "bought": 109000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 360,
    "roi": null,
    "performance": null
  },
  {
    "rank": 98,
    "name": "Diego Araújo",
    "level": "C",
    "state": "SC",
    "bought": 149000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 960,
    "roi": null,
    "performance": null
  },
  {
    "rank": 99,
    "name": "Diego Nascimento",
    "level": "D",
    "state": "SP",
    "bought": 108000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 470,
    "roi": null,
    "performance": null
  },
  {
    "rank": 100,
    "name": "Camila Alves",
    "level": "D",
    "state": "PR",
    "bought": 148000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 220,
    "roi": null,
    "performance": null
  },
  {
    "rank": 101,
    "name": "Camila Moraes",
    "level": "D",
    "state": "SP",
    "bought": 67000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 830,
    "roi": null,
    "performance": null
  },
  {
    "rank": 102,
    "name": "Camila Lima",
    "level": "C",
    "state": "PE",
    "bought": 107000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 580,
    "roi": null,
    "performance": null
  },
  {
    "rank": 103,
    "name": "Camila Ribeiro",
    "level": "D",
    "state": "SP",
    "bought": 66000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 940,
    "roi": null,
    "performance": null
  },
  {
    "rank": 104,
    "name": "Thiago Souza",
    "level": "C",
    "state": "RS",
    "bought": 106000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 700,
    "roi": null,
    "performance": null
  },
  {
    "rank": 105,
    "name": "Thiago Costa",
    "level": "D",
    "state": "SP",
    "bought": 65000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 200,
    "roi": null,
    "performance": null
  },
  {
    "rank": 106,
    "name": "Thiago Almeida",
    "level": "C",
    "state": "SC",
    "bought": 105000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 810,
    "roi": null,
    "performance": null
  },
  {
    "rank": 107,
    "name": "Beatriz Nascimento",
    "level": "D",
    "state": "SP",
    "bought": 64000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 320,
    "roi": null,
    "performance": null
  },
  {
    "rank": 108,
    "name": "Beatriz Freitas",
    "level": "D",
    "state": "RJ",
    "bought": 143000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 680,
    "roi": null,
    "performance": null
  },
  {
    "rank": 109,
    "name": "Beatriz Rodrigues",
    "level": "D",
    "state": "GO",
    "bought": 63000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 430,
    "roi": null,
    "performance": null
  },
  {
    "rank": 110,
    "name": "Rodrigo Gomes",
    "level": "D",
    "state": "SP",
    "bought": 142000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 790,
    "roi": null,
    "performance": null
  },
  {
    "rank": 111,
    "name": "Rodrigo Souza",
    "level": "D",
    "state": "BA",
    "bought": 61000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 540,
    "roi": null,
    "performance": null
  },
  {
    "rank": 112,
    "name": "Rodrigo Oliveira",
    "level": "D",
    "state": "SP",
    "bought": 140000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 900,
    "roi": null,
    "performance": null
  },
  {
    "rank": 113,
    "name": "Larissa Ferreira",
    "level": "D",
    "state": "RJ",
    "bought": 100000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 410,
    "roi": null,
    "performance": null
  },
  {
    "rank": 114,
    "name": "Larissa Araújo",
    "level": "D",
    "state": "SP",
    "bought": 139000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 170,
    "roi": null,
    "performance": null
  },
  {
    "rank": 115,
    "name": "Larissa Freitas",
    "level": "D",
    "state": "RJ",
    "bought": 98000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 530,
    "roi": null,
    "performance": null
  },
  {
    "rank": 116,
    "name": "Larissa Alves",
    "level": "D",
    "state": "SP",
    "bought": 138000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 280,
    "roi": null,
    "performance": null
  },
  {
    "rank": 117,
    "name": "Felipe Lima",
    "level": "D",
    "state": "SP",
    "bought": 97000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 640,
    "roi": null,
    "performance": null
  },
  {
    "rank": 118,
    "name": "Felipe Silva",
    "level": "D",
    "state": "PE",
    "bought": 137000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 390,
    "roi": null,
    "performance": null
  },
  {
    "rank": 119,
    "name": "Felipe Ribeiro",
    "level": "C",
    "state": "MG",
    "bought": 56000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 1000,
    "roi": null,
    "performance": null
  },
  {
    "rank": 120,
    "name": "Felipe Oliveira",
    "level": "D",
    "state": "SP",
    "bought": 96000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 750,
    "roi": null,
    "performance": null
  },
  {
    "rank": 121,
    "name": "Isabela Costa",
    "level": "C",
    "state": "RJ",
    "bought": 55000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 260,
    "roi": null,
    "performance": null
  },
  {
    "rank": 122,
    "name": "Isabela Almeida",
    "level": "D",
    "state": "SP",
    "bought": 95000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 870,
    "roi": null,
    "performance": null
  },
  {
    "rank": 123,
    "name": "Isabela Nascimento",
    "level": "C",
    "state": "RJ",
    "bought": 54000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 370,
    "roi": null,
    "performance": null
  },
  {
    "rank": 124,
    "name": "Isabela Alves",
    "level": "D",
    "state": "SP",
    "bought": 94000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 980,
    "roi": null,
    "performance": null
  },
  {
    "rank": 125,
    "name": "Gustavo Rodrigues",
    "level": "D",
    "state": "RJ",
    "bought": 53000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 490,
    "roi": null,
    "performance": null
  },
  {
    "rank": 126,
    "name": "Gustavo Gomes",
    "level": "C",
    "state": "MG",
    "bought": 132000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 850,
    "roi": null,
    "performance": null
  },
  {
    "rank": 127,
    "name": "Gustavo Souza",
    "level": "D",
    "state": "SP",
    "bought": 51000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 600,
    "roi": null,
    "performance": null
  },
  {
    "rank": 128,
    "name": "Vanessa Costa",
    "level": "C",
    "state": "MG",
    "bought": 131000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 960,
    "roi": null,
    "performance": null
  },
  {
    "rank": 129,
    "name": "Vanessa Carvalho",
    "level": "D",
    "state": "SP",
    "bought": 50000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 710,
    "roi": null,
    "performance": null
  },
  {
    "rank": 130,
    "name": "Vanessa Araújo",
    "level": "C",
    "state": "RJ",
    "bought": 129000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 220,
    "roi": null,
    "performance": null
  },
  {
    "rank": 131,
    "name": "Eduardo Freitas",
    "level": "D",
    "state": "SC",
    "bought": 89000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 580,
    "roi": null,
    "performance": null
  },
  {
    "rank": 132,
    "name": "Eduardo Rodrigues",
    "level": "C",
    "state": "RJ",
    "bought": 128000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 340,
    "roi": null,
    "performance": null
  },
  {
    "rank": 133,
    "name": "Eduardo Lima",
    "level": "D",
    "state": "PR",
    "bought": 87000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 690,
    "roi": null,
    "performance": null
  },
  {
    "rank": 134,
    "name": "Letícia Silva",
    "level": "C",
    "state": "SP",
    "bought": 127000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 450,
    "roi": null,
    "performance": null
  },
  {
    "rank": 135,
    "name": "Letícia Oliveira",
    "level": "D",
    "state": "MG",
    "bought": 86000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 810,
    "roi": null,
    "performance": null
  },
  {
    "rank": 136,
    "name": "Letícia Costa",
    "level": "D",
    "state": "RS",
    "bought": 45000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 320,
    "roi": null,
    "performance": null
  },
  {
    "rank": 137,
    "name": "Marcelo Almeida",
    "level": "C",
    "state": "RJ",
    "bought": 85000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 920,
    "roi": null,
    "performance": null
  },
  {
    "rank": 138,
    "name": "Marcelo Nascimento",
    "level": "D",
    "state": "SC",
    "bought": 44000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 430,
    "roi": null,
    "performance": null
  },
  {
    "rank": 139,
    "name": "Marcelo Alves",
    "level": "C",
    "state": "RJ",
    "bought": 84000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 180,
    "roi": null,
    "performance": null
  },
  {
    "rank": 140,
    "name": "Priscila Rodrigues",
    "level": "D",
    "state": "PR",
    "bought": 43000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 540,
    "roi": null,
    "performance": null
  },
  {
    "rank": 141,
    "name": "Priscila Barbosa",
    "level": "C",
    "state": "RJ",
    "bought": 82000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 300,
    "roi": null,
    "performance": null
  },
  {
    "rank": 142,
    "name": "Priscila Souza",
    "level": "D",
    "state": "MG",
    "bought": 42000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 660,
    "roi": null,
    "performance": null
  },
  {
    "rank": 143,
    "name": "Leonardo Costa",
    "level": "D",
    "state": "BA",
    "bought": 121000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 170,
    "roi": null,
    "performance": null
  },
  {
    "rank": 144,
    "name": "Leonardo Almeida",
    "level": "D",
    "state": "MG",
    "bought": 40000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 770,
    "roi": null,
    "performance": null
  },
  {
    "rank": 145,
    "name": "Leonardo Araújo",
    "level": "D",
    "state": "RS",
    "bought": 120000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 280,
    "roi": null,
    "performance": null
  },
  {
    "rank": 146,
    "name": "Leonardo Pereira",
    "level": "D",
    "state": "RJ",
    "bought": 39000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 880,
    "roi": null,
    "performance": null
  },
  {
    "rank": 147,
    "name": "Daniela Rodrigues",
    "level": "D",
    "state": "SC",
    "bought": 118000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 390,
    "roi": null,
    "performance": null
  },
  {
    "rank": 148,
    "name": "Daniela Lima",
    "level": "D",
    "state": "SP",
    "bought": 78000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 750,
    "roi": null,
    "performance": null
  },
  {
    "rank": 149,
    "name": "Daniela Silva",
    "level": "D",
    "state": "PR",
    "bought": 117000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 510,
    "roi": null,
    "performance": null
  },
  {
    "rank": 150,
    "name": "Vinícius Oliveira",
    "level": "D",
    "state": "PE",
    "bought": 76000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 860,
    "roi": null,
    "performance": null
  },
  {
    "rank": 151,
    "name": "Vinícius Carvalho",
    "level": "D",
    "state": "MG",
    "bought": 116000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 620,
    "roi": null,
    "performance": null
  },
  {
    "rank": 152,
    "name": "Vinícius Almeida",
    "level": "D",
    "state": "RS",
    "bought": 75000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 980,
    "roi": null,
    "performance": null
  },
  {
    "rank": 153,
    "name": "Andressa Nascimento",
    "level": "C",
    "state": "SP",
    "bought": 34000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 490,
    "roi": null,
    "performance": null
  },
  {
    "rank": 154,
    "name": "Andressa Alves",
    "level": "D",
    "state": "SC",
    "bought": 74000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 240,
    "roi": null,
    "performance": null
  },
  {
    "rank": 155,
    "name": "Andressa Lima",
    "level": "C",
    "state": "SP",
    "bought": 33000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 600,
    "roi": null,
    "performance": null
  },
  {
    "rank": 156,
    "name": "Gabriel Barbosa",
    "level": "D",
    "state": "PR",
    "bought": 73000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 350,
    "roi": null,
    "performance": null
  },
  {
    "rank": 157,
    "name": "Gabriel Souza",
    "level": "C",
    "state": "GO",
    "bought": 32000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 710,
    "roi": null,
    "performance": null
  },
  {
    "rank": 158,
    "name": "Gabriel Martins",
    "level": "D",
    "state": "MG",
    "bought": 71000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 470,
    "roi": null,
    "performance": null
  },
  {
    "rank": 159,
    "name": "Gabriel Costa",
    "level": "D",
    "state": "SP",
    "bought": 111000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 220,
    "roi": null,
    "performance": null
  },
  {
    "rank": 160,
    "name": "Monique Almeida",
    "level": "D",
    "state": "BA",
    "bought": 31000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 830,
    "roi": null,
    "performance": null
  },
  {
    "rank": 161,
    "name": "Monique Araújo",
    "level": "C",
    "state": "SP",
    "bought": 110000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 330,
    "roi": null,
    "performance": null
  },
  {
    "rank": 162,
    "name": "Monique Pereira",
    "level": "D",
    "state": "RS",
    "bought": 149000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 940,
    "roi": null,
    "performance": null
  },
  {
    "rank": 163,
    "name": "Carlos Rodrigues",
    "level": "C",
    "state": "SP",
    "bought": 109000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 450,
    "roi": null,
    "performance": null
  },
  {
    "rank": 164,
    "name": "Carlos Barbosa",
    "level": "D",
    "state": "SC",
    "bought": 148000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 200,
    "roi": null,
    "performance": null
  },
  {
    "rank": 165,
    "name": "Carlos Silva",
    "level": "C",
    "state": "SP",
    "bought": 107000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 560,
    "roi": null,
    "performance": null
  },
  {
    "rank": 166,
    "name": "Ana Oliveira",
    "level": "D",
    "state": "SP",
    "bought": 67000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 920,
    "roi": null,
    "performance": null
  },
  {
    "rank": 167,
    "name": "Ana Carvalho",
    "level": "C",
    "state": "PE",
    "bought": 106000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 670,
    "roi": null,
    "performance": null
  },
  {
    "rank": 168,
    "name": "Ana Araújo",
    "level": "D",
    "state": "SP",
    "bought": 65000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 180,
    "roi": null,
    "performance": null
  },
  {
    "rank": 169,
    "name": "Ana Santos",
    "level": "C",
    "state": "RS",
    "bought": 105000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 790,
    "roi": null,
    "performance": null
  },
  {
    "rank": 170,
    "name": "Pedro Alves",
    "level": "D",
    "state": "SP",
    "bought": 64000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 300,
    "roi": null,
    "performance": null
  },
  {
    "rank": 171,
    "name": "Pedro Lima",
    "level": "D",
    "state": "RJ",
    "bought": 143000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 660,
    "roi": null,
    "performance": null
  },
  {
    "rank": 172,
    "name": "Pedro Silva",
    "level": "C",
    "state": "SP",
    "bought": 63000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 410,
    "roi": null,
    "performance": null
  },
  {
    "rank": 173,
    "name": "Juliana Souza",
    "level": "D",
    "state": "RJ",
    "bought": 142000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 770,
    "roi": null,
    "performance": null
  },
  {
    "rank": 174,
    "name": "Juliana Martins",
    "level": "C",
    "state": "GO",
    "bought": 62000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 520,
    "roi": null,
    "performance": null
  },
  {
    "rank": 175,
    "name": "Juliana Almeida",
    "level": "D",
    "state": "SP",
    "bought": 141000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 880,
    "roi": null,
    "performance": null
  },
  {
    "rank": 176,
    "name": "Juliana Santos",
    "level": "C",
    "state": "BA",
    "bought": 60000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 640,
    "roi": null,
    "performance": null
  },
  {
    "rank": 177,
    "name": "Rafael Araújo",
    "level": "D",
    "state": "MG",
    "bought": 100000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 390,
    "roi": null,
    "performance": null
  },
  {
    "rank": 178,
    "name": "Rafael Pereira",
    "level": "D",
    "state": "SP",
    "bought": 140000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 1000,
    "roi": null,
    "performance": null
  },
  {
    "rank": 179,
    "name": "Rafael Rodrigues",
    "level": "D",
    "state": "RJ",
    "bought": 99000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 500,
    "roi": null,
    "performance": null
  },
  {
    "rank": 180,
    "name": "Rafael Barbosa",
    "level": "D",
    "state": "SP",
    "bought": 138000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 260,
    "roi": null,
    "performance": null
  },
  {
    "rank": 181,
    "name": "Fernanda Souza",
    "level": "D",
    "state": "RJ",
    "bought": 98000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 620,
    "roi": null,
    "performance": null
  },
  {
    "rank": 182,
    "name": "Fernanda Ribeiro",
    "level": "D",
    "state": "SP",
    "bought": 137000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 370,
    "roi": null,
    "performance": null
  },
  {
    "rank": 183,
    "name": "Fernanda Carvalho",
    "level": "D",
    "state": "SP",
    "bought": 96000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 730,
    "roi": null,
    "performance": null
  },
  {
    "rank": 184,
    "name": "Lucas Araújo",
    "level": "D",
    "state": "MG",
    "bought": 56000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 240,
    "roi": null,
    "performance": null
  },
  {
    "rank": 185,
    "name": "Lucas Pereira",
    "level": "D",
    "state": "SP",
    "bought": 95000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 840,
    "roi": null,
    "performance": null
  },
  {
    "rank": 186,
    "name": "Lucas Alves",
    "level": "D",
    "state": "RJ",
    "bought": 54000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 350,
    "roi": null,
    "performance": null
  },
  {
    "rank": 187,
    "name": "Mariana Moraes",
    "level": "D",
    "state": "SP",
    "bought": 94000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 960,
    "roi": null,
    "performance": null
  },
  {
    "rank": 188,
    "name": "Mariana Silva",
    "level": "D",
    "state": "RJ",
    "bought": 53000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 470,
    "roi": null,
    "performance": null
  },
  {
    "rank": 189,
    "name": "Mariana Souza",
    "level": "C",
    "state": "PR",
    "bought": 132000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 830,
    "roi": null,
    "performance": null
  },
  {
    "rank": 190,
    "name": "Bruno Martins",
    "level": "D",
    "state": "RJ",
    "bought": 52000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 580,
    "roi": null,
    "performance": null
  },
  {
    "rank": 191,
    "name": "Bruno Almeida",
    "level": "C",
    "state": "MG",
    "bought": 131000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 940,
    "roi": null,
    "performance": null
  },
  {
    "rank": 192,
    "name": "Bruno Santos",
    "level": "D",
    "state": "SP",
    "bought": 51000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 690,
    "roi": null,
    "performance": null
  },
  {
    "rank": 193,
    "name": "Amanda Pereira",
    "level": "C",
    "state": "MG",
    "bought": 130000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 200,
    "roi": null,
    "performance": null
  },
  {
    "rank": 194,
    "name": "Amanda Freitas",
    "level": "D",
    "state": "SP",
    "bought": 49000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 810,
    "roi": null,
    "performance": null
  },
  {
    "rank": 195,
    "name": "Amanda Rodrigues",
    "level": "D",
    "state": "RS",
    "bought": 89000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 560,
    "roi": null,
    "performance": null
  },
  {
    "rank": 196,
    "name": "Amanda Barbosa",
    "level": "D",
    "state": "RJ",
    "bought": 129000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 310,
    "roi": null,
    "performance": null
  },
  {
    "rank": 197,
    "name": "Diego Souza",
    "level": "C",
    "state": "SC",
    "bought": 88000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 670,
    "roi": null,
    "performance": null
  },
  {
    "rank": 198,
    "name": "Diego Martins",
    "level": "D",
    "state": "RJ",
    "bought": 127000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 430,
    "roi": null,
    "performance": null
  },
  {
    "rank": 199,
    "name": "Diego Carvalho",
    "level": "C",
    "state": "PR",
    "bought": 87000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 790,
    "roi": null,
    "performance": null
  },
  {
    "rank": 200,
    "name": "Diego Ferreira",
    "level": "D",
    "state": "SP",
    "bought": 126000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 540,
    "roi": null,
    "performance": null
  },
  {
    "rank": 201,
    "name": "Camila Pereira",
    "level": "C",
    "state": "MG",
    "bought": 85000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 900,
    "roi": null,
    "performance": null
  },
  {
    "rank": 202,
    "name": "Camila Alves",
    "level": "D",
    "state": "RS",
    "bought": 44000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 410,
    "roi": null,
    "performance": null
  },
  {
    "rank": 203,
    "name": "Camila Moraes",
    "level": "C",
    "state": "RJ",
    "bought": 84000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 160,
    "roi": null,
    "performance": null
  },
  {
    "rank": 204,
    "name": "Thiago Silva",
    "level": "D",
    "state": "SC",
    "bought": 43000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 520,
    "roi": null,
    "performance": null
  },
  {
    "rank": 205,
    "name": "Thiago Ribeiro",
    "level": "C",
    "state": "RJ",
    "bought": 83000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 280,
    "roi": null,
    "performance": null
  },
  {
    "rank": 206,
    "name": "Thiago Martins",
    "level": "D",
    "state": "PR",
    "bought": 42000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 640,
    "roi": null,
    "performance": null
  },
  {
    "rank": 207,
    "name": "Beatriz Almeida",
    "level": "D",
    "state": "SP",
    "bought": 121000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 990,
    "roi": null,
    "performance": null
  },
  {
    "rank": 208,
    "name": "Beatriz Santos",
    "level": "C",
    "state": "MG",
    "bought": 41000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 750,
    "roi": null,
    "performance": null
  },
  {
    "rank": 209,
    "name": "Beatriz Alves",
    "level": "D",
    "state": "BA",
    "bought": 120000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 260,
    "roi": null,
    "performance": null
  },
  {
    "rank": 210,
    "name": "Rodrigo Freitas",
    "level": "C",
    "state": "MG",
    "bought": 40000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 860,
    "roi": null,
    "performance": null
  },
  {
    "rank": 211,
    "name": "Rodrigo Barbosa",
    "level": "D",
    "state": "RS",
    "bought": 119000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 370,
    "roi": null,
    "performance": null
  },
  {
    "rank": 212,
    "name": "Rodrigo Souza",
    "level": "D",
    "state": "SP",
    "bought": 78000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 730,
    "roi": null,
    "performance": null
  },
  {
    "rank": 213,
    "name": "Larissa Martins",
    "level": "D",
    "state": "SC",
    "bought": 118000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 480,
    "roi": null,
    "performance": null
  },
  {
    "rank": 214,
    "name": "Larissa Carvalho",
    "level": "D",
    "state": "SP",
    "bought": 77000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 840,
    "roi": null,
    "performance": null
  },
  {
    "rank": 215,
    "name": "Larissa Ferreira",
    "level": "D",
    "state": "PR",
    "bought": 116000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 600,
    "roi": null,
    "performance": null
  },
  {
    "rank": 216,
    "name": "Felipe Pereira",
    "level": "D",
    "state": "PE",
    "bought": 75000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 960,
    "roi": null,
    "performance": null
  },
  {
    "rank": 217,
    "name": "Felipe Freitas",
    "level": "D",
    "state": "MG",
    "bought": 115000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 710,
    "roi": null,
    "performance": null
  },
  {
    "rank": 218,
    "name": "Felipe Moraes",
    "level": "D",
    "state": "RS",
    "bought": 74000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 220,
    "roi": null,
    "performance": null
  },
  {
    "rank": 219,
    "name": "Isabela Silva",
    "level": "D",
    "state": "SP",
    "bought": 33000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 580,
    "roi": null,
    "performance": null
  },
  {
    "rank": 220,
    "name": "Isabela Ribeiro",
    "level": "D",
    "state": "SC",
    "bought": 73000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 330,
    "roi": null,
    "performance": null
  },
  {
    "rank": 221,
    "name": "Isabela Carvalho",
    "level": "D",
    "state": "SP",
    "bought": 32000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 690,
    "roi": null,
    "performance": null
  },
  {
    "rank": 222,
    "name": "Isabela Costa",
    "level": "D",
    "state": "PR",
    "bought": 72000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 450,
    "roi": null,
    "performance": null
  },
  {
    "rank": 223,
    "name": "Gustavo Santos",
    "level": "D",
    "state": "SP",
    "bought": 31000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 800,
    "roi": null,
    "performance": null
  },
  {
    "rank": 224,
    "name": "Gustavo Alves",
    "level": "C",
    "state": "SP",
    "bought": 110000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 310,
    "roi": null,
    "performance": null
  },
  {
    "rank": 225,
    "name": "Gustavo Moraes",
    "level": "D",
    "state": "BA",
    "bought": 150000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 920,
    "roi": null,
    "performance": null
  },
  {
    "rank": 226,
    "name": "Vanessa Barbosa",
    "level": "C",
    "state": "SP",
    "bought": 109000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 430,
    "roi": null,
    "performance": null
  },
  {
    "rank": 227,
    "name": "Vanessa Gomes",
    "level": "D",
    "state": "RS",
    "bought": 149000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 180,
    "roi": null,
    "performance": null
  },
  {
    "rank": 228,
    "name": "Vanessa Martins",
    "level": "C",
    "state": "SP",
    "bought": 108000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 540,
    "roi": null,
    "performance": null
  },
  {
    "rank": 229,
    "name": "Eduardo Carvalho",
    "level": "D",
    "state": "RJ",
    "bought": 67000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 900,
    "roi": null,
    "performance": null
  },
  {
    "rank": 230,
    "name": "Eduardo Ferreira",
    "level": "D",
    "state": "SP",
    "bought": 106000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 650,
    "roi": null,
    "performance": null
  },
  {
    "rank": 231,
    "name": "Eduardo Pereira",
    "level": "C",
    "state": "SP",
    "bought": 66000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 160,
    "roi": null,
    "performance": null
  },
  {
    "rank": 232,
    "name": "Eduardo Freitas",
    "level": "D",
    "state": "PE",
    "bought": 105000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 770,
    "roi": null,
    "performance": null
  },
  {
    "rank": 233,
    "name": "Letícia Barbosa",
    "level": "C",
    "state": "SP",
    "bought": 64000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 280,
    "roi": null,
    "performance": null
  },
  {
    "rank": 234,
    "name": "Letícia Lima",
    "level": "D",
    "state": "RS",
    "bought": 104000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 880,
    "roi": null,
    "performance": null
  },
  {
    "rank": 235,
    "name": "Letícia Silva",
    "level": "D",
    "state": "RJ",
    "bought": 144000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 630,
    "roi": null,
    "performance": null
  },
  {
    "rank": 236,
    "name": "Letícia Ribeiro",
    "level": "C",
    "state": "SP",
    "bought": 63000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 390,
    "roi": null,
    "performance": null
  },
  {
    "rank": 237,
    "name": "Marcelo Carvalho",
    "level": "D",
    "state": "RJ",
    "bought": 142000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 750,
    "roi": null,
    "performance": null
  },
  {
    "rank": 238,
    "name": "Marcelo Ferreira",
    "level": "C",
    "state": "SP",
    "bought": 62000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 500,
    "roi": null,
    "performance": null
  },
  {
    "rank": 239,
    "name": "Marcelo Santos",
    "level": "D",
    "state": "RJ",
    "bought": 141000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 860,
    "roi": null,
    "performance": null
  },
  {
    "rank": 240,
    "name": "Priscila Nascimento",
    "level": "C",
    "state": "SP",
    "bought": 61000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 620,
    "roi": null,
    "performance": null
  },
  {
    "rank": 241,
    "name": "Priscila Moraes",
    "level": "D",
    "state": "SP",
    "bought": 140000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 970,
    "roi": null,
    "performance": null
  },
  {
    "rank": 242,
    "name": "Priscila Barbosa",
    "level": "D",
    "state": "MG",
    "bought": 99000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 480,
    "roi": null,
    "performance": null
  },
  {
    "rank": 243,
    "name": "Leonardo Gomes",
    "level": "C",
    "state": "SP",
    "bought": 139000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 240,
    "roi": null,
    "performance": null
  },
  {
    "rank": 244,
    "name": "Leonardo Martins",
    "level": "D",
    "state": "RJ",
    "bought": 98000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 600,
    "roi": null,
    "performance": null
  },
  {
    "rank": 245,
    "name": "Leonardo Costa",
    "level": "C",
    "state": "SP",
    "bought": 137000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 350,
    "roi": null,
    "performance": null
  },
  {
    "rank": 246,
    "name": "Daniela Ferreira",
    "level": "D",
    "state": "RJ",
    "bought": 97000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 710,
    "roi": null,
    "performance": null
  },
  {
    "rank": 247,
    "name": "Daniela Pereira",
    "level": "D",
    "state": "PR",
    "bought": 56000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 220,
    "roi": null,
    "performance": null
  },
  {
    "rank": 248,
    "name": "Daniela Freitas",
    "level": "D",
    "state": "SP",
    "bought": 95000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 820,
    "roi": null,
    "performance": null
  },
  {
    "rank": 249,
    "name": "Vinícius Barbosa",
    "level": "D",
    "state": "MG",
    "bought": 55000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 330,
    "roi": null,
    "performance": null
  },
  {
    "rank": 250,
    "name": "Vinícius Lima",
    "level": "D",
    "state": "SP",
    "bought": 94000,
    "soldLabel": "Em negociação",
    "sold": null,
    "profit": null,
    "traffic": 940,
    "roi": null,
    "performance": null
  }
];

export const biMentoradosProspecting = [
  {
    "rank": 1,
    "name": "Mariana Ribeiro",
    "state": "RS",
    "bought": 76000,
    "traffic": 890,
    "leads": 43,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 2,
    "name": "Mariana Souza",
    "state": "RJ",
    "bought": 116000,
    "traffic": 640,
    "leads": 23,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 3,
    "name": "Mariana Costa",
    "state": "SC",
    "bought": 75000,
    "traffic": 1000,
    "leads": 49,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 4,
    "name": "Bruno Santos",
    "state": "SP",
    "bought": 34000,
    "traffic": 510,
    "leads": 38,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 5,
    "name": "Bruno Nascimento",
    "state": "PR",
    "bought": 74000,
    "traffic": 260,
    "leads": 13,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 6,
    "name": "Bruno Freitas",
    "state": "GO",
    "bought": 33000,
    "traffic": 620,
    "leads": 47,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 7,
    "name": "Bruno Rodrigues",
    "state": "MG",
    "bought": 72000,
    "traffic": 370,
    "leads": 19,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 8,
    "name": "Amanda Gomes",
    "state": "BA",
    "bought": 32000,
    "traffic": 730,
    "leads": 57,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 9,
    "name": "Amanda Ribeiro",
    "state": "SP",
    "bought": 111000,
    "traffic": 240,
    "leads": 9,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 10,
    "name": "Amanda Oliveira",
    "state": "RS",
    "bought": 30000,
    "traffic": 850,
    "leads": 68,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 11,
    "name": "Diego Ferreira",
    "state": "SP",
    "bought": 109000,
    "traffic": 360,
    "leads": 14,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 12,
    "name": "Diego Araújo",
    "state": "SC",
    "bought": 149000,
    "traffic": 960,
    "leads": 79,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 13,
    "name": "Diego Nascimento",
    "state": "SP",
    "bought": 108000,
    "traffic": 470,
    "leads": 19,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 14,
    "name": "Camila Alves",
    "state": "PR",
    "bought": 148000,
    "traffic": 220,
    "leads": 19,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 15,
    "name": "Camila Moraes",
    "state": "SP",
    "bought": 67000,
    "traffic": 830,
    "leads": 45,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 16,
    "name": "Camila Lima",
    "state": "PE",
    "bought": 107000,
    "traffic": 580,
    "leads": 23,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 17,
    "name": "Camila Ribeiro",
    "state": "SP",
    "bought": 66000,
    "traffic": 940,
    "leads": 52,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 18,
    "name": "Thiago Souza",
    "state": "RS",
    "bought": 106000,
    "traffic": 700,
    "leads": 29,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 19,
    "name": "Thiago Costa",
    "state": "SP",
    "bought": 65000,
    "traffic": 200,
    "leads": 11,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 20,
    "name": "Thiago Almeida",
    "state": "SC",
    "bought": 105000,
    "traffic": 810,
    "leads": 33,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 21,
    "name": "Beatriz Nascimento",
    "state": "SP",
    "bought": 64000,
    "traffic": 320,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 22,
    "name": "Beatriz Freitas",
    "state": "RJ",
    "bought": 143000,
    "traffic": 680,
    "leads": 65,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 23,
    "name": "Beatriz Rodrigues",
    "state": "GO",
    "bought": 63000,
    "traffic": 430,
    "leads": 25,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 24,
    "name": "Rodrigo Gomes",
    "state": "SP",
    "bought": 142000,
    "traffic": 790,
    "leads": 78,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 25,
    "name": "Rodrigo Souza",
    "state": "BA",
    "bought": 61000,
    "traffic": 540,
    "leads": 32,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 26,
    "name": "Rodrigo Oliveira",
    "state": "SP",
    "bought": 140000,
    "traffic": 900,
    "leads": 92,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 27,
    "name": "Larissa Ferreira",
    "state": "RJ",
    "bought": 100000,
    "traffic": 410,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 28,
    "name": "Larissa Araújo",
    "state": "SP",
    "bought": 139000,
    "traffic": 170,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 29,
    "name": "Larissa Freitas",
    "state": "RJ",
    "bought": 98000,
    "traffic": 530,
    "leads": 24,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 30,
    "name": "Larissa Alves",
    "state": "SP",
    "bought": 138000,
    "traffic": 280,
    "leads": 31,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 31,
    "name": "Felipe Lima",
    "state": "SP",
    "bought": 97000,
    "traffic": 640,
    "leads": 29,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 32,
    "name": "Felipe Silva",
    "state": "PE",
    "bought": 137000,
    "traffic": 390,
    "leads": 45,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 33,
    "name": "Felipe Ribeiro",
    "state": "MG",
    "bought": 56000,
    "traffic": 1000,
    "leads": 66,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 34,
    "name": "Felipe Oliveira",
    "state": "SP",
    "bought": 96000,
    "traffic": 750,
    "leads": 34,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 35,
    "name": "Isabela Costa",
    "state": "RJ",
    "bought": 55000,
    "traffic": 260,
    "leads": 17,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 36,
    "name": "Isabela Almeida",
    "state": "SP",
    "bought": 95000,
    "traffic": 870,
    "leads": 41,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 37,
    "name": "Isabela Nascimento",
    "state": "RJ",
    "bought": 54000,
    "traffic": 370,
    "leads": 25,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 38,
    "name": "Isabela Alves",
    "state": "SP",
    "bought": 94000,
    "traffic": 980,
    "leads": 46,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 39,
    "name": "Gustavo Rodrigues",
    "state": "RJ",
    "bought": 53000,
    "traffic": 490,
    "leads": 34,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 40,
    "name": "Gustavo Gomes",
    "state": "MG",
    "bought": 132000,
    "traffic": 850,
    "leads": 31,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 41,
    "name": "Gustavo Souza",
    "state": "SP",
    "bought": 51000,
    "traffic": 600,
    "leads": 43,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 42,
    "name": "Vanessa Costa",
    "state": "MG",
    "bought": 131000,
    "traffic": 960,
    "leads": 36,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 43,
    "name": "Vanessa Carvalho",
    "state": "SP",
    "bought": 50000,
    "traffic": 710,
    "leads": 52,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 44,
    "name": "Vanessa Araújo",
    "state": "RJ",
    "bought": 129000,
    "traffic": 220,
    "leads": 8,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 45,
    "name": "Eduardo Freitas",
    "state": "SC",
    "bought": 89000,
    "traffic": 580,
    "leads": 29,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 46,
    "name": "Eduardo Rodrigues",
    "state": "RJ",
    "bought": 128000,
    "traffic": 340,
    "leads": 13,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 47,
    "name": "Eduardo Lima",
    "state": "PR",
    "bought": 87000,
    "traffic": 690,
    "leads": 36,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 48,
    "name": "Letícia Silva",
    "state": "SP",
    "bought": 127000,
    "traffic": 450,
    "leads": 17,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 49,
    "name": "Letícia Oliveira",
    "state": "MG",
    "bought": 86000,
    "traffic": 810,
    "leads": 42,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 50,
    "name": "Letícia Costa",
    "state": "RS",
    "bought": 45000,
    "traffic": 320,
    "leads": 26,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 51,
    "name": "Marcelo Almeida",
    "state": "RJ",
    "bought": 85000,
    "traffic": 920,
    "leads": 49,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 52,
    "name": "Marcelo Nascimento",
    "state": "SC",
    "bought": 44000,
    "traffic": 430,
    "leads": 36,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 53,
    "name": "Marcelo Alves",
    "state": "RJ",
    "bought": 84000,
    "traffic": 180,
    "leads": 10,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 54,
    "name": "Priscila Rodrigues",
    "state": "PR",
    "bought": 43000,
    "traffic": 540,
    "leads": 47,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 55,
    "name": "Priscila Barbosa",
    "state": "RJ",
    "bought": 82000,
    "traffic": 300,
    "leads": 17,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 56,
    "name": "Priscila Souza",
    "state": "MG",
    "bought": 42000,
    "traffic": 660,
    "leads": 59,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 57,
    "name": "Leonardo Costa",
    "state": "BA",
    "bought": 121000,
    "traffic": 170,
    "leads": 7,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 58,
    "name": "Leonardo Almeida",
    "state": "MG",
    "bought": 40000,
    "traffic": 770,
    "leads": 71,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 59,
    "name": "Leonardo Araújo",
    "state": "RS",
    "bought": 120000,
    "traffic": 280,
    "leads": 12,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 60,
    "name": "Leonardo Pereira",
    "state": "RJ",
    "bought": 39000,
    "traffic": 880,
    "leads": 84,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 61,
    "name": "Daniela Rodrigues",
    "state": "SC",
    "bought": 118000,
    "traffic": 390,
    "leads": 17,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 62,
    "name": "Daniela Lima",
    "state": "SP",
    "bought": 78000,
    "traffic": 750,
    "leads": 45,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 63,
    "name": "Daniela Silva",
    "state": "PR",
    "bought": 117000,
    "traffic": 510,
    "leads": 22,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 64,
    "name": "Vinícius Oliveira",
    "state": "PE",
    "bought": 76000,
    "traffic": 860,
    "leads": 53,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 65,
    "name": "Vinícius Carvalho",
    "state": "MG",
    "bought": 116000,
    "traffic": 620,
    "leads": 27,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 66,
    "name": "Vinícius Almeida",
    "state": "RS",
    "bought": 75000,
    "traffic": 980,
    "leads": 61,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 67,
    "name": "Andressa Nascimento",
    "state": "SP",
    "bought": 34000,
    "traffic": 490,
    "leads": 54,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 68,
    "name": "Andressa Alves",
    "state": "SC",
    "bought": 74000,
    "traffic": 240,
    "leads": 15,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 69,
    "name": "Andressa Lima",
    "state": "SP",
    "bought": 33000,
    "traffic": 600,
    "leads": 69,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 70,
    "name": "Gabriel Barbosa",
    "state": "PR",
    "bought": 73000,
    "traffic": 350,
    "leads": 23,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 71,
    "name": "Gabriel Souza",
    "state": "GO",
    "bought": 32000,
    "traffic": 710,
    "leads": 84,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 72,
    "name": "Gabriel Martins",
    "state": "MG",
    "bought": 71000,
    "traffic": 470,
    "leads": 31,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 73,
    "name": "Gabriel Costa",
    "state": "SP",
    "bought": 111000,
    "traffic": 220,
    "leads": 10,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 74,
    "name": "Monique Almeida",
    "state": "BA",
    "bought": 31000,
    "traffic": 830,
    "leads": 103,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 75,
    "name": "Monique Araújo",
    "state": "SP",
    "bought": 110000,
    "traffic": 330,
    "leads": 16,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 76,
    "name": "Monique Pereira",
    "state": "RS",
    "bought": 149000,
    "traffic": 940,
    "leads": 34,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 77,
    "name": "Carlos Rodrigues",
    "state": "SP",
    "bought": 109000,
    "traffic": 450,
    "leads": 22,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 78,
    "name": "Carlos Barbosa",
    "state": "SC",
    "bought": 148000,
    "traffic": 200,
    "leads": 7,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 79,
    "name": "Carlos Silva",
    "state": "SP",
    "bought": 107000,
    "traffic": 560,
    "leads": 27,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 80,
    "name": "Ana Oliveira",
    "state": "SP",
    "bought": 67000,
    "traffic": 920,
    "leads": 68,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 81,
    "name": "Ana Carvalho",
    "state": "PE",
    "bought": 106000,
    "traffic": 670,
    "leads": 33,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 82,
    "name": "Ana Araújo",
    "state": "SP",
    "bought": 65000,
    "traffic": 180,
    "leads": 14,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 83,
    "name": "Ana Santos",
    "state": "RS",
    "bought": 105000,
    "traffic": 790,
    "leads": 40,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 84,
    "name": "Pedro Alves",
    "state": "SP",
    "bought": 64000,
    "traffic": 300,
    "leads": 23,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 85,
    "name": "Pedro Lima",
    "state": "RJ",
    "bought": 143000,
    "traffic": 660,
    "leads": 25,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 86,
    "name": "Pedro Silva",
    "state": "SP",
    "bought": 63000,
    "traffic": 410,
    "leads": 33,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 87,
    "name": "Juliana Souza",
    "state": "RJ",
    "bought": 142000,
    "traffic": 770,
    "leads": 30,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 88,
    "name": "Juliana Martins",
    "state": "GO",
    "bought": 62000,
    "traffic": 520,
    "leads": 43,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 89,
    "name": "Juliana Almeida",
    "state": "SP",
    "bought": 141000,
    "traffic": 880,
    "leads": 35,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 90,
    "name": "Juliana Santos",
    "state": "BA",
    "bought": 60000,
    "traffic": 640,
    "leads": 54,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 91,
    "name": "Rafael Araújo",
    "state": "MG",
    "bought": 100000,
    "traffic": 390,
    "leads": 21,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 92,
    "name": "Rafael Pereira",
    "state": "SP",
    "bought": 140000,
    "traffic": 1000,
    "leads": 40,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 93,
    "name": "Rafael Rodrigues",
    "state": "RJ",
    "bought": 99000,
    "traffic": 500,
    "leads": 28,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 94,
    "name": "Rafael Barbosa",
    "state": "SP",
    "bought": 138000,
    "traffic": 260,
    "leads": 11,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 95,
    "name": "Fernanda Souza",
    "state": "RJ",
    "bought": 98000,
    "traffic": 620,
    "leads": 35,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 96,
    "name": "Fernanda Ribeiro",
    "state": "SP",
    "bought": 137000,
    "traffic": 370,
    "leads": 15,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 97,
    "name": "Fernanda Carvalho",
    "state": "SP",
    "bought": 96000,
    "traffic": 730,
    "leads": 42,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 98,
    "name": "Lucas Araújo",
    "state": "MG",
    "bought": 56000,
    "traffic": 240,
    "leads": 23,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 99,
    "name": "Lucas Pereira",
    "state": "SP",
    "bought": 95000,
    "traffic": 840,
    "leads": 49,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 100,
    "name": "Lucas Alves",
    "state": "RJ",
    "bought": 54000,
    "traffic": 350,
    "leads": 34,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 101,
    "name": "Mariana Moraes",
    "state": "SP",
    "bought": 94000,
    "traffic": 960,
    "leads": 57,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 102,
    "name": "Mariana Silva",
    "state": "RJ",
    "bought": 53000,
    "traffic": 470,
    "leads": 48,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 103,
    "name": "Mariana Souza",
    "state": "PR",
    "bought": 132000,
    "traffic": 830,
    "leads": 36,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 104,
    "name": "Bruno Martins",
    "state": "RJ",
    "bought": 52000,
    "traffic": 580,
    "leads": 61,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 105,
    "name": "Bruno Almeida",
    "state": "MG",
    "bought": 131000,
    "traffic": 940,
    "leads": 42,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 106,
    "name": "Bruno Santos",
    "state": "SP",
    "bought": 51000,
    "traffic": 690,
    "leads": 75,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 107,
    "name": "Amanda Pereira",
    "state": "MG",
    "bought": 130000,
    "traffic": 200,
    "leads": 9,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 108,
    "name": "Amanda Freitas",
    "state": "SP",
    "bought": 49000,
    "traffic": 810,
    "leads": 92,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 109,
    "name": "Amanda Rodrigues",
    "state": "RS",
    "bought": 89000,
    "traffic": 560,
    "leads": 36,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 110,
    "name": "Amanda Barbosa",
    "state": "RJ",
    "bought": 129000,
    "traffic": 310,
    "leads": 14,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 111,
    "name": "Diego Souza",
    "state": "SC",
    "bought": 88000,
    "traffic": 670,
    "leads": 45,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 112,
    "name": "Diego Martins",
    "state": "RJ",
    "bought": 127000,
    "traffic": 430,
    "leads": 20,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 113,
    "name": "Diego Carvalho",
    "state": "PR",
    "bought": 87000,
    "traffic": 790,
    "leads": 54,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 114,
    "name": "Diego Ferreira",
    "state": "SP",
    "bought": 126000,
    "traffic": 540,
    "leads": 25,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 115,
    "name": "Camila Pereira",
    "state": "MG",
    "bought": 85000,
    "traffic": 900,
    "leads": 63,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 116,
    "name": "Camila Alves",
    "state": "RS",
    "bought": 44000,
    "traffic": 410,
    "leads": 15,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 117,
    "name": "Camila Moraes",
    "state": "RJ",
    "bought": 84000,
    "traffic": 160,
    "leads": 11,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 118,
    "name": "Thiago Silva",
    "state": "SC",
    "bought": 43000,
    "traffic": 520,
    "leads": 19,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 119,
    "name": "Thiago Ribeiro",
    "state": "RJ",
    "bought": 83000,
    "traffic": 280,
    "leads": 21,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 120,
    "name": "Thiago Martins",
    "state": "PR",
    "bought": 42000,
    "traffic": 640,
    "leads": 24,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 121,
    "name": "Beatriz Almeida",
    "state": "SP",
    "bought": 121000,
    "traffic": 990,
    "leads": 50,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 122,
    "name": "Beatriz Santos",
    "state": "MG",
    "bought": 41000,
    "traffic": 750,
    "leads": 28,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 123,
    "name": "Beatriz Alves",
    "state": "BA",
    "bought": 120000,
    "traffic": 260,
    "leads": 13,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 124,
    "name": "Rodrigo Freitas",
    "state": "MG",
    "bought": 40000,
    "traffic": 860,
    "leads": 33,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 125,
    "name": "Rodrigo Barbosa",
    "state": "RS",
    "bought": 119000,
    "traffic": 370,
    "leads": 19,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 126,
    "name": "Rodrigo Souza",
    "state": "SP",
    "bought": 78000,
    "traffic": 730,
    "leads": 59,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 127,
    "name": "Larissa Martins",
    "state": "SC",
    "bought": 118000,
    "traffic": 480,
    "leads": 25,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 128,
    "name": "Larissa Carvalho",
    "state": "SP",
    "bought": 77000,
    "traffic": 840,
    "leads": 70,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 129,
    "name": "Larissa Ferreira",
    "state": "PR",
    "bought": 116000,
    "traffic": 600,
    "leads": 32,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 130,
    "name": "Felipe Pereira",
    "state": "PE",
    "bought": 75000,
    "traffic": 960,
    "leads": 83,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 131,
    "name": "Felipe Freitas",
    "state": "MG",
    "bought": 115000,
    "traffic": 710,
    "leads": 39,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 132,
    "name": "Felipe Moraes",
    "state": "RS",
    "bought": 74000,
    "traffic": 220,
    "leads": 20,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 133,
    "name": "Isabela Silva",
    "state": "SP",
    "bought": 33000,
    "traffic": 580,
    "leads": 24,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 134,
    "name": "Isabela Ribeiro",
    "state": "SC",
    "bought": 73000,
    "traffic": 330,
    "leads": 30,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 135,
    "name": "Isabela Carvalho",
    "state": "SP",
    "bought": 32000,
    "traffic": 690,
    "leads": 29,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 136,
    "name": "Isabela Costa",
    "state": "PR",
    "bought": 72000,
    "traffic": 450,
    "leads": 43,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 137,
    "name": "Gustavo Santos",
    "state": "SP",
    "bought": 31000,
    "traffic": 800,
    "leads": 34,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 138,
    "name": "Gustavo Alves",
    "state": "SP",
    "bought": 110000,
    "traffic": 310,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 139,
    "name": "Gustavo Moraes",
    "state": "BA",
    "bought": 150000,
    "traffic": 920,
    "leads": 39,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 140,
    "name": "Vanessa Barbosa",
    "state": "SP",
    "bought": 109000,
    "traffic": 430,
    "leads": 26,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 141,
    "name": "Vanessa Gomes",
    "state": "RS",
    "bought": 149000,
    "traffic": 180,
    "leads": 8,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 142,
    "name": "Vanessa Martins",
    "state": "SP",
    "bought": 108000,
    "traffic": 540,
    "leads": 34,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 143,
    "name": "Eduardo Carvalho",
    "state": "RJ",
    "bought": 67000,
    "traffic": 900,
    "leads": 98,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 144,
    "name": "Eduardo Ferreira",
    "state": "SP",
    "bought": 106000,
    "traffic": 650,
    "leads": 41,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 145,
    "name": "Eduardo Pereira",
    "state": "SP",
    "bought": 66000,
    "traffic": 160,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 146,
    "name": "Eduardo Freitas",
    "state": "PE",
    "bought": 105000,
    "traffic": 770,
    "leads": 50,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 147,
    "name": "Letícia Barbosa",
    "state": "SP",
    "bought": 64000,
    "traffic": 280,
    "leads": 33,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 148,
    "name": "Letícia Lima",
    "state": "RS",
    "bought": 104000,
    "traffic": 880,
    "leads": 58,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 149,
    "name": "Letícia Silva",
    "state": "RJ",
    "bought": 144000,
    "traffic": 630,
    "leads": 29,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 150,
    "name": "Letícia Ribeiro",
    "state": "SP",
    "bought": 63000,
    "traffic": 390,
    "leads": 48,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 151,
    "name": "Marcelo Carvalho",
    "state": "RJ",
    "bought": 142000,
    "traffic": 750,
    "leads": 35,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 152,
    "name": "Marcelo Ferreira",
    "state": "SP",
    "bought": 62000,
    "traffic": 500,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 153,
    "name": "Marcelo Santos",
    "state": "RJ",
    "bought": 141000,
    "traffic": 860,
    "leads": 41,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 154,
    "name": "Priscila Nascimento",
    "state": "SP",
    "bought": 61000,
    "traffic": 620,
    "leads": 23,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 155,
    "name": "Priscila Moraes",
    "state": "SP",
    "bought": 140000,
    "traffic": 970,
    "leads": 47,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 156,
    "name": "Priscila Barbosa",
    "state": "MG",
    "bought": 99000,
    "traffic": 480,
    "leads": 35,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 157,
    "name": "Leonardo Gomes",
    "state": "SP",
    "bought": 139000,
    "traffic": 240,
    "leads": 12,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 158,
    "name": "Leonardo Martins",
    "state": "RJ",
    "bought": 98000,
    "traffic": 600,
    "leads": 45,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 159,
    "name": "Leonardo Costa",
    "state": "SP",
    "bought": 137000,
    "traffic": 350,
    "leads": 18,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 160,
    "name": "Daniela Ferreira",
    "state": "RJ",
    "bought": 97000,
    "traffic": 710,
    "leads": 55,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 161,
    "name": "Daniela Pereira",
    "state": "PR",
    "bought": 56000,
    "traffic": 220,
    "leads": 8,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 162,
    "name": "Daniela Freitas",
    "state": "SP",
    "bought": 95000,
    "traffic": 820,
    "leads": 65,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 163,
    "name": "Vinícius Barbosa",
    "state": "MG",
    "bought": 55000,
    "traffic": 330,
    "leads": 13,
    "status": "🔄 Prospectando"
  },
  {
    "rank": 164,
    "name": "Vinícius Lima",
    "state": "SP",
    "bought": 94000,
    "traffic": 940,
    "leads": 76,
    "status": "🔄 Prospectando"
  }
];
